### ISSUE TITLE
TODO List (Enhancement, mostly about the report)

### ISSUE THREAD

**Issue by BenjaminJoly** [CASES-LU/diagnostic#11]
- [x] ~~Correct the report, mostly by using reviewed ones (Text which appears twice, typo correction ...).~~
- [x] ~~Modify language files (PO/MO) to use new terms more appropriate (Maturity fragile/basic/optimised, or terms which MONARC use like "Existing control")~~
- [x] ~~Change the graph Maturity Evolution by one which is more significant. (Correlate with recommendations ?)~~
- [x] ~~Change the qualification level (Managed, More or Less Managed, Planned and Not Managed) to fragile/basic/optimised and Non-Applicable (N/A).~~
- [x] ~~Change calcul method :~~
    - ~~Optimised = 1/1~~
    - ~~Basic = 0.5/1~~
    - ~~Fragile = 0/1~~
    - ~~N/A = 0/0 (Not calculated or taken in the final percentage)~~
- [x] ~~Change the category colours in the compliance graph, corresponding by their percentage (< 33% red, >66% green, between orange, colours from MONARC.)~~
- [x] ~~Changes icons ![gravity_3](https://github.com/CASES-LU/diagnostic/raw/master/public/img/gravity_3.png) by red points like in MONARC.~~
- [x] ~~Use the MONARC colours in the report to indicate maturity in the detailed tab (And do not put icons anymore). Grey colour should be the one for N/A.~~
- [x] ~~Put legend before tabs in the report.~~
- [x] ~~Replace CASES icon for Diagnostic Icon (In the report and in the application)~~
- [x] ~~Add in language file columns of the tabs in the report (And add it in generations for the report).~~
- [x] ~~Add language (German needed)~~
